# Retentioneering — API showcase

This notebook exercises every public `Eventstream` method on the bundled e-commerce dataset: here is the input, here is the call, here is the output, and here is what each argument means. No storytelling — for a narrative analytics walkthrough see `ecom_demo.ipynb`.

Two intended uses:

- **Users** — skim top to bottom to learn what each tool does and how its arguments work. Every section links to the corresponding page of the [documentation](https://retentioneering.com/docs/).
- **Developers** — run top to bottom as a smoke test: no cell should raise, and every widget should render.

Widget cells only use **data parameters** (the ones that change the computed result). Display parameters (`height`, `sidebar_open`, ...) are deliberately left at their defaults — see the per-widget documentation pages for those.

## Setup

The dataset: six months of a consumer-electronics store — 600 users, ~3600 sessions, ~31000 events, 19 event types, plus four segment columns. The [schema](https://retentioneering.com/docs/eventstream#schema) declares column roles. `path_cols` defines what a *path* is (see [Key concepts](https://retentioneering.com/docs/eventstream#key-concepts)): the first column is the default grain (here — the whole user journey), and every tool accepts a `path_col` override to switch to session grain.

In [1]:
import pandas as pd

import retentioneering as rete

df = rete.datasets.load_ecom(as_dataframe=True)

stream = rete.Eventstream(
    df,
    schema={
        "path_cols": ["user_id", "session_id"],
        "segment_cols": [
            "platform",
            "acquisition_channel",
            "user_cohort",
            "user_lifecycle",
        ],
    },
)

# A user with a purchase — used below to show before/after transformations
USER = df.loc[df["event"] == "purchase", "user_id"].iloc[0]

print(f"rows: {len(df):,}   users: {df['user_id'].nunique()}   demo user: {USER}")
df.head()

rows: 31,106   users: 600   demo user: user_0000

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning

## 1. Eventstream basics

Docs: [Eventstream](https://retentioneering.com/docs/eventstream).

`Eventstream` wraps the dataframe and exposes everything else as methods. Basic introspection first.

In [2]:
# The data back as a plain DataFrame.
# exclude_start_end=True (default) hides the synthetic path_start/path_end rows.
stream.to_dataframe().head()

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5

In [3]:
# How many times each event occurs
counts = stream.get_event_counts()
dict(sorted(counts.items(), key=lambda kv: -kv[1]))

{'product_view': 6851,
 'catalog': 6521,
 'search': 4011,
 'home': 2762,
 'filter_results': 2610,
 'add_to_cart': 1346,
 'cart': 1204,
 'shipping_details': 958,
 'wishlist_add': 812,
 'promo_page': 796,
 'payment_details': 709,
 'account_page': 659,
 'purchase': 470,
 'review_page': 406,
 'support_chat': 277,
 'error_page': 276,
 'compare': 275,
 'payment_error': 119,
 'checkout_bug': 44}

In [4]:
# Declared segment columns and their values
stream.get_segment_levels()

{'platform': ['desktop', 'mobile', 'tablet'],
 'acquisition_channel': ['direct',
  'email',
  'organic',
  'paid_search',
  'social'],
 'user_cohort': ['2024-01', '2024-02', '2024-03', '2024-04'],
 'user_lifecycle': ['loyal', 'new', 'returning']}

In [5]:
# is_empty()  — cheap emptiness check
# fingerprint — stable content hash of the data shape / event distribution
# equals()    — compare two eventstreams
print("is_empty:", stream.is_empty())
print("fingerprint:", stream.fingerprint)
print("equals(itself + no-op filter):", stream.equals(stream.filter_events()))

is_empty: False
fingerprint: 9d915314a230ec76eb5d19586bc27513
equals(itself + no-op filter): True

In [6]:
# describe() — quick sanity-check summary: schema, shape, date range,
# event frequency, and per-path length/duration stats
summary = stream.describe()
print("shape:", summary["shape"])
print("date_range:", summary["date_range"])
summary["path_stats"]["user_id"]

shape: {'n_events': 31106, 'n_paths': 600, 'n_unique_events': 19}
date_range: {'min': Timestamp('2024-01-04 11:45:38'), 'max': Timestamp('2024-06-29 21:57:38'), 'span': Timedelta('177 days 10:12:00')}

           length      duration
count  600.000000  6.000000e+02
mean    51.843333  7.212163e+06
std     21.236300  2.802266e+06
min      5.000000  2.544810e+05
25%     35.000000  5.072117e+06
50%     51.000000  7.084552e+06
75%     68.000000  9.153876e+06
90%     79.000000  1.102810e+07
99%    101.050000  1.399769e+07
max    113.000000  1.478713e+07

### Metrics used throughout this notebook

Docs: [Path Metrics](https://retentioneering.com/docs/path-metrics).

Two metric lists are reused below wherever a `metrics`/`features` argument is expected — Segment Overview, Cluster Analysis, `get_metrics`, `filter_paths`. `SHORT_METRICS` is a minimal, general-purpose default. `FULL_METRICS` has one entry per metric in the registry, including `has_all_events`/`has_any_event` — the AND/OR combinators used below.

In [7]:
# A short, general-purpose metric list — reasonable default for a quick look
SHORT_METRICS = [{"metric": "length"}, {"metric": "event_count_bulk"}]

# One entry per metric in retentioneering.metrics.metric_builder.VALID_METRICS —
# reused below for Segment Overview, Cluster Analysis, get_metrics, and filter_paths
FULL_METRICS = [
    {"metric": "length", "agg": "mean"},
    {"metric": "duration", "agg": "median"},
    {"metric": "event_count", "metric_args": {"event": "purchase"}, "agg": "mean"},
    {"metric": "has_event", "metric_args": {"event": "purchase"}, "agg": "mean"},
    {
        "metric": "event_count_bulk",
        "metric_args": {"events": ["purchase", "add_to_cart", "search"]},
        "agg": "mean",
    },
    {
        "metric": "has_event_bulk",
        "metric_args": {"events": ["purchase", "add_to_cart", "search"]},
        "agg": "mean",
    },
    {
        # AND semantics: both events occurred somewhere in the path
        "metric": "has_all_events",
        "metric_args": {"events": ["add_to_cart", "purchase"]},
        "agg": "mean",
    },
    {
        # OR semantics: either event occurred
        "metric": "has_any_event",
        "metric_args": {"events": ["promo_page", "wishlist_add"]},
        "agg": "mean",
    },
    {
        "metric": "time_between",
        "metric_args": {"start_event": "path_start", "end_event": "purchase"},
        "agg": "median",
    },
    {"metric": "first_event_time", "agg": "q5"},
    {"metric": "active_days", "agg": "mean"},
    {
        "metric": "matches_pattern",
        "metric_args": {"pattern": "search->.*->purchase"},
        "agg": "mean",
    },
    {
        "metric": "in_segment",
        "metric_args": {
            "segment_name": "user_lifecycle",
            "segment_level": "loyal",
            "mode": "any",
        },
        "agg": "complement_distance",
    },
]
len(FULL_METRICS)

13

## 2. Widgets

Docs: [Widgets](https://retentioneering.com/docs/widgets).

Common behavior for all widgets:

- every data parameter is also editable live in the **sidebar** — no need to
  re-run the cell;
- every widget has a headless `*_data()` twin returning raw data
  ([headless mode](https://retentioneering.com/docs/widgets#headless-mode));
- every widget supports [diff mode](https://retentioneering.com/docs/widgets#diff-mode)
  in two shapes: `diff=(segment_col, value1, value2)` overlays two segment
  values (red = `value1` higher, blue = `value2` higher; the reserved
  `"<REST>"` as `value2` means "everyone else"), or `diff=(path_ids1, path_ids2)`
  compares two explicit groups of path IDs instead;
- every widget accepts a `state_file` path to persist its full configuration
  across reruns (see [Saving widget state](https://retentioneering.com/docs/widgets#saving-widget-state)
  below).

### Transition Graph — basic

Docs: [Transition Graph](https://retentioneering.com/docs/widgets/transition-graph).

Nodes are events, edges are transitions. `edge_weight` picks the edge value: `proba_out` (default) / `proba_in` — transition probabilities out of the source / into the target; `count`; `unique_paths`; `share_of_total`; `avg_per_path`; `time_median` / `time_q95` (seconds).

In [8]:
stream.transition_graph()

### Saving widget state

Docs: [Saving widget state](https://retentioneering.com/docs/widgets#saving-widget-state).

`state_file` binds the widget to a JSON file: created on first run, loaded on every subsequent one, and auto-saved on every change — data and display parameters plus UI extras like node layout and zoom.

In [9]:
import tempfile

state_path = f"{tempfile.mkdtemp()}/transition_graph_state.json"
stream.transition_graph(state_file=state_path)

### Transition Graph — diff mode

Two segments in one graph: red means `value1` is higher, blue means `value2` is higher. Try `diff=["platform", "mobile", "<REST>"]` for one-vs-everyone-else.

In [10]:
stream.transition_graph(diff=["platform", "mobile", "desktop"])

### Transition Graph — diff by path-id groups

`diff` also accepts `(path_ids1, path_ids2)` — two explicit groups of path IDs — to compare arbitrary cohorts without a segment column.

In [11]:
purchasers = df.loc[df["event"] == "purchase", "user_id"].unique().tolist()
non_purchasers = [u for u in df["user_id"].unique() if u not in set(purchasers)]
stream.transition_graph(diff=(purchasers, non_purchasers))

In [12]:
# Headless twin: the transition matrix as an events x events DataFrame
tm = stream.transition_graph_data(edge_weight="count")
tm.iloc[:8, :8]

next_event,path_start,account_page,add_to_cart,cart,catalog,checkout_bug,compare,error_page
event,,,,,,,,
path_start,0,0,0,0,174,0,0,0
account_page,0,1,15,22,182,1,3,3
add_to_cart,0,24,3,1029,138,0,0,16
cart,0,16,3,0,119,0,0,13
catalog,0,112,5,0,743,0,0,50
checkout_bug,0,0,41,0,1,0,0,0
compare,0,5,67,0,55,0,0,2
error_page,0,2,16,16,55,1,6,0

### Step Matrix — basic

Docs: [Step Matrix](https://retentioneering.com/docs/widgets/step-matrix).

A heatmap of `P(event | step)`: each column is an ordinal step of the path and sums to 1. `max_steps` controls how many steps are computed.

In [13]:
stream.step_matrix(max_steps=12)

### Step Matrix — path_pattern

`path_pattern` is a `->`-separated sequence of anchor events where `.*` matches any run of events. Paths are filtered to those matching the pattern, and each anchor gets its own matrix block with steps counted relative to it (negative = before the anchor). A serrated edge means paths continue beyond the visible range.

In [14]:
stream.step_matrix(path_pattern="add_to_cart->.*->purchase")

### Step Matrix — diff mode

In diff mode each column sums to 0: cells show the share difference
`value1 − value2`. Here: new users vs. everyone else (`"<REST>"`).

In [15]:
stream.step_matrix(diff=["user_lifecycle", "new", "<REST>"])

### Step Matrix — path_pattern + diff mode

`path_pattern` and `diff` combine cleanly — the combined matrix keeps the same `value1 − value2` sign as diff mode alone.

In [16]:
stream.step_matrix(
    path_pattern="add_to_cart->.*->purchase",
    diff=["user_lifecycle", "new", "<REST>"],
)

In [17]:
# Headless twin (shared with Step Sankey): a single DataFrame (no path_pattern -> one block)
step_matrix_data = stream.step_matrix_data(max_steps=8)
step_matrix_data.round(3)

step                0      1      2      3      4      5      6      7      8
event
path_start        1.0  0.000  0.000  0.000  0.000  0.000  0.000  0.000  0.000
account_page      0.0  0.000  0.037  0.013  0.025  0.018  0.032  0.022  0.008
add_to_cart       0.0  0.000  0.008  0.022  0.040  0.037  0.020  0.033  0.040
cart              0.0  0.000  0.000  0.008  0.017  0.033  0.027  0.020  0.027
catalog           0.0  0.290  0.247  0.277  0.230  0.247  0.228  0.225  0.198
checkout_bug      0.0  0.000  0.000  0.000  0.000  0.000  0.002  0.002  0.000
compare           0.0  0.000  0.000  0.002  0.010  0.010  0.007  0.013  0.012
error_page        0.0  0.000  0.000  0.003  0.012  0.010  0.008  0.012  0.012
filter_results    0.0  0.000  0.103  0.127  0.098  0.103  0.108  0.093  0.083
home              0.0  0.428  0.073  0.085  0.080  0.067  0.102  0.095  0.098
payment_details   0.0  0.000  0.000  0.000  0.000  0.002  0.008  0.017  0.012
product_view      0.0  0.080  0.198  0.252  0.267  0.250  0.230  0.245  0.238
promo_page        0.0  0.000  0.078  0.018  0.025  0.018  0.028  0.017  0.028
purchase          0.0  0.000  0.000  0.000  0.000  0.000  0.002  0.008  0.017
review_page       0.0  0.000  0.005  0.012  0.008  0.015  0.015  0.012  0.025
search            0.0  0.202  0.240  0.133  0.160  0.137  0.112  0.143  0.145
shipping_details  0.0  0.000  0.000  0.000  0.002  0.013  0.028  0.015  0.015
support_chat      0.0  0.000  0.000  0.007  0.007  0.003  0.007  0.002  0.003
wishlist_add      0.0  0.000  0.010  0.042  0.020  0.037  0.033  0.023  0.035
path_end          0.0  0.000  0.000  0.000  0.000  0.000  0.003  0.003  0.003

### Step Sankey — basic

Docs: [Step Sankey](https://retentioneering.com/docs/widgets/step-sankey).

The same per-step data as Step Matrix, drawn as a flow diagram — use whichever makes the pattern easier to spot. Same `max_steps`, `path_pattern`, and `diff` arguments.

In [18]:
stream.step_sankey(max_steps=8)

### Step Sankey — path_pattern

In [19]:
stream.step_sankey(path_pattern="catalog->.*->purchase")

### Step Sankey — diff mode

In [20]:
stream.step_sankey(diff=["acquisition_channel", "paid_search", "organic"])

### Funnel — basic

Docs: [Funnel](https://retentioneering.com/docs/widgets/funnel).

Sequential semantics: a path counts at step N only if that step's event occurs **after** all previous steps already happened.

In [21]:
stream.funnel(steps=["catalog", "add_to_cart", "cart", "purchase"])

### Funnel — diff mode

In [22]:
stream.funnel(
    steps=["catalog", "add_to_cart", "cart", "purchase"],
    diff=["platform", "mobile", "desktop"],
)

In [23]:
# Headless twin: conversion numbers as a dict
stream.funnel_data(steps=["catalog", "add_to_cart", "cart", "purchase"])

{'steps': [{'step': 'catalog',
   'unique_paths': 600,
   'conversion_rate': 1.0,
   'step_conversion_rate': 1.0},
  {'step': 'add_to_cart',
   'unique_paths': 512,
   'conversion_rate': 0.8533333333333334,
   'step_conversion_rate': 0.8533333333333334},
  {'step': 'cart',
   'unique_paths': 483,
   'conversion_rate': 0.805,
   'step_conversion_rate': 0.943359375},
  {'step': 'purchase',
   'unique_paths': 321,
   'conversion_rate': 0.535,
   'step_conversion_rate': 0.6645962732919255}]}

### Segment Overview

Docs: [Segment Overview](https://retentioneering.com/docs/widgets/segment-overview),
[Path Metrics](https://retentioneering.com/docs/path-metrics).

Rows are metrics, columns are segment values; `segment_size` and `segment_share` are always added. Each metric carries an `agg` — `mean`, `median`, `q5`/`q25`/`q75`/`q95`, or `complement_distance` (Wasserstein distance between this segment's distribution and everyone else's: higher = more distinctive). **Click** a cell to see the metric's distribution for that segment; **shift-click** a second cell in the same row to compare two. The config below is `FULL_METRICS`, defined above — one metric from the registry per row.

In [24]:
stream.segment_overview(
    segment_col="user_lifecycle",
    metrics=FULL_METRICS,
)

In [25]:
# Headless twin: the same table as a DataFrame
stream.segment_overview_data(
    segment_col="platform",
    metrics=[
        {"metric": "length", "agg": "mean"},
        {"metric": "has_event", "metric_args": {"event": "purchase"}, "agg": "mean"},
    ],
).round(3)

                         desktop   mobile   tablet
metric
segment_size             392.000  297.000  107.000
segment_share              0.492    0.373    0.134
length_mean               41.189   38.226   33.710
has_event_purchase_mean    0.482    0.330    0.458

### Cluster Analysis

Docs: [Cluster Analysis](https://retentioneering.com/docs/widgets/cluster-analysis).

Clusters paths by behavioral `features` and shows a Segment Overview-style heatmap of `overview_metrics` for the resulting clusters. Both arguments take configs from the same [Path Metrics](https://retentioneering.com/docs/path-metrics) registry — features are the clustering *input*, overview metrics *describe* the output. Quick pass below uses `SHORT_METRICS`; full pass uses `FULL_METRICS` for both arguments.

**How the optimal-split search works.** The chosen `method`'s own parameters travel in `method_args`; for kmeans that is `n_clusters`, which accepts a single int, a list, or a range string like `"3-6"`. For a list/range the widget runs a grid search: for every candidate *k* it fits KMeans and computes the **silhouette score** (how much closer each path is to its own cluster than to the nearest other one, from −1 to 1; on a sample of up to 2 000 paths for speed). The *k* with the best score wins, and the whole score curve is drawn in the widget so you can see how close the runner-ups were. The same grid mechanism works for `nmf_components` (NMF decomposition of the feature matrix, toggleable in the sidebar) and, with the `hdbscan` method, for `min_cluster_size` / `cluster_selection_epsilon`.

In [26]:
# Quick pass: SHORT_METRICS (length + per-event counts) is often enough
stream.cluster_analysis(features=SHORT_METRICS, method_args={"n_clusters": "3-6"})

Full pass — every metric in the registry as both `features` and `overview_metrics`:

In [27]:
stream.cluster_analysis(
    features=FULL_METRICS,
    overview_metrics=FULL_METRICS,
    method="kmeans",
    scaler="minmax",
    method_args={"n_clusters": "3-6"},
)

In [28]:
# Headless twin: the silhouette grid is returned as data, so you can inspect
# exactly what the search saw
result = stream.cluster_analysis_data(
    features=[
        {"metric": "length"},
        {
            "metric": "event_count_bulk",
            "metric_args": {"events": ["purchase", "add_to_cart"]},
        },
    ],
    method_args={"n_clusters": [3, 4, 5, 6]},
)
for params, score in zip(
    result["silhouette"]["params"], result["silhouette"]["silhouette"]
):
    print(params, "-> silhouette", round(score, 3))
result["overview_df"].round(3)

{'n_clusters': 3} -> silhouette 0.35
{'n_clusters': 4} -> silhouette 0.292
{'n_clusters': 5} -> silhouette 0.346
{'n_clusters': 6} -> silhouette 0.36

,cluster_0,cluster_1,cluster_2,cluster_3,cluster_4,cluster_5
metric,,,,,,
segment_size,151.000,62.000,119.000,39.000,93.000,136.000
segment_share,0.252,0.103,0.198,0.065,0.155,0.227

## 3. Data processors

Docs: [Data processors](https://retentioneering.com/docs/data-processors).

Every processor returns a **new** `Eventstream` — the original is never modified, so calls chain freely. Each cell below starts from the same `stream` and renders the resulting dataframe, so you can see exactly how the rows were transformed.

In [29]:
def peek(s, user=None, n=10):
    """First rows of a resulting eventstream, optionally for one user."""
    out = s.to_dataframe()
    if user is not None:
        out = out[out["user_id"] == user]
    return out.head(n)

### filter_events — keep rows

Docs: [Filter Events](https://retentioneering.com/docs/data-processors/filter-events).

Four mutually exclusive modes, one argument each: `keep`, `drop`, `func`, `sql`. `keep` takes a `{column: values}` mapping; multiple columns combine with **AND** (a row must match every entry).

In [30]:
res = stream.filter_events(
    keep={"event": ["add_to_cart", "purchase"], "platform": ["mobile"]}
)
peek(res)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0004,sess_000028,add_to_cart,2024-03-30 14:05:09,mobile,social,2024-02,returning,raw,2.0,17
1,user_0005,sess_000032,add_to_cart,2024-06-04 15:16:53,mobile,paid_search,2024-04,returning,raw,2.0,5
2,user_0005,sess_000034,add_to_cart,2024-06-11 14:30:40,mobile,paid_search,2024-04,returning,raw,2.0,34
3,user_0010,sess_000058,add_to_cart,2024-04-21 20:32:12,mobile,paid_search,2024-03,returning,raw,2.0,11
4,user_0010,sess_000059,add_to_cart,2024-06-06 09:03:36,mobile,paid_search,2024-03,loyal,raw,2.0,38
5,user_0010,sess_000059,add_to_cart,2024-06-06 09:23:49,mobile,paid_search,2024-03,loyal,raw,2.0,50
6,user_0010,sess_000061,add_to_cart,2024-06-12 12:40:57,mobile,paid_search,2024-03,loyal,raw,2.0,57
7,user_0010,sess_000061,purchase,2024-06-12 12:47:07,mobile,paid_search,2024-03,loyal,raw,2.0,61
8,user_0010,sess_000062,add_to_cart,2024-06-14 14:04:19,mobile,paid_search,2024-03,loyal,raw,2.0,67
9,user_0010,sess_000062,purchase,2024-06-14 14:08:44,mobile,paid_search,2024-03,loyal,raw,2.0,71

### filter_events — drop rows

Same `{column: values}` format, but removes matches. Multiple columns combine with **OR** (a row is removed if it matches *any* entry) — the exact complement of `keep`.

In [31]:
res = stream.filter_events(
    drop={"event": ["support_chat", "error_page"], "platform": ["tablet"]}
)
peek(res)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10

### filter_events — Python predicate

`func` receives the raw DataFrame and returns a boolean mask; `True` rows are kept.

In [32]:
res = stream.filter_events(func=lambda d: d["timestamp"].dt.month == 3)  # March only
peek(res)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10

### filter_events — SQL

`sql` takes a DuckDB SELECT that reads from the fixed alias `eventstream` and returns all original columns.

In [33]:
res = stream.filter_events(
    sql="SELECT * FROM eventstream WHERE event NOT LIKE '%_error'"
)
peek(res)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10

### filter_paths — keep whole paths by metric conditions

Docs: [Filter Paths](https://retentioneering.com/docs/data-processors/filter-paths), [Path Metrics](https://retentioneering.com/docs/path-metrics) (the full metric list).

Unlike `filter_events` (row-level), `filter_paths` keeps or drops **entire paths**. The condition is a tree of comparisons over per-path metrics; operators are `=` (or `==`), `!=`, `>`, `<`, `>=`, `<=`, combined with `and` / `or` / `not` nodes.

In [34]:
# Paths that contain at least one purchase
res = stream.filter_paths(
    {
        "op": ">",
        "metric": "event_count",
        "value": 0,
        "metric_args": {"event": "purchase"},
    }
)
print("users kept:", res.to_dataframe()["user_id"].nunique())
peek(res)

users kept: 328

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10

In [35]:
# A top-level list is shorthand for AND: long paths that follow cart -> ... -> purchase
res = stream.filter_paths(
    [
        {"op": ">", "metric": "length", "value": 20},
        {
            "op": "=",
            "metric": "matches_pattern",
            "value": True,
            "metric_args": {"pattern": "add_to_cart->.*->purchase"},
        },
    ]
)
print("users kept:", res.to_dataframe()["user_id"].nunique())
peek(res)

users kept: 323

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10

### filter_paths — AND / OR conditions with has_all_events / has_any_event

`has_all_events` (AND semantics) and `has_any_event` (OR semantics) each reduce a list of events to a single boolean per path, so they combine like any other condition — no special multi-event syntax needed. A top-level list is still shorthand for AND, so this keeps only paths that satisfy **both** conditions below.

In [36]:
# AND: both add_to_cart and purchase occurred somewhere in the path
# OR: either promo_page or wishlist_add occurred
res = stream.filter_paths(
    [
        {
            "op": "=",
            "metric": "has_all_events",
            "value": True,
            "metric_args": {"events": ["add_to_cart", "purchase"]},
        },
        {
            "op": "=",
            "metric": "has_any_event",
            "value": True,
            "metric_args": {"events": ["promo_page", "wishlist_add"]},
        },
    ]
)
print("users kept:", res.to_dataframe()["user_id"].nunique())
peek(res)

users kept: 300

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10

### add_events — from source events

Docs: [Add Events](https://retentioneering.com/docs/data-processors/add-events).

Inserts synthetic events; original rows are kept. In `source_event` mode one event is inserted per path, at the timestamp of the **first** occurrence of any source event.

In [37]:
res = stream.add_events("first_cart_touch", source_event=["add_to_cart", "cart"])
peek(res, user=USER)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
3,user_0000,sess_000001,first_cart_touch,2024-03-13 10:23:35,desktop,email,2024-01,returning,synthetic,1.0,4
4,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
5,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5
6,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6
7,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7
8,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8
9,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9

### add_events — from SQL

Every row returned by the query (alias `eventstream`, same columns) becomes a new synthetic event named `name`.

In [38]:
res = stream.add_events(
    "payment_issue", sql="SELECT * FROM eventstream WHERE event = 'payment_error'"
)
res.to_dataframe().query("event == 'payment_issue'").head()

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
374,user_0006,sess_000043,payment_issue,2024-05-23 13:25:39,desktop,paid_search,2024-01,loyal,synthetic,1.0,93
504,user_0009,sess_000056,payment_issue,2024-05-27 12:55:21,desktop,organic,2024-01,loyal,synthetic,1.0,32
628,user_0011,sess_000065,payment_issue,2024-05-21 17:01:41,mobile,paid_search,2024-04,new,synthetic,1.0,44
684,user_0013,sess_000071,payment_issue,2024-05-26 09:42:37,tablet,organic,2024-04,returning,synthetic,1.0,14
889,user_0017,sess_000095,payment_issue,2024-05-29 16:00:06,desktop,email,2024-01,loyal,synthetic,1.0,51

### add_events — churn marker

`churn` inserts an event after a period of inactivity: `inactivity_days` is the gap threshold; optional `active_events` restricts what counts as activity.

In [39]:
res = stream.add_events(
    "churned",
    churn={"inactivity_days": 30, "active_events": ["purchase", "add_to_cart"]},
)
res.to_dataframe().query("event == 'churned'").head()

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
17,user_0000,sess_000002,churned,2024-03-23 09:51:52,desktop,email,2024-01,returning,churn,3.0,17
26,user_0000,sess_000005,churned,2024-04-30 19:35:38,desktop,email,2024-01,loyal,churn,3.0,25
97,user_0001,sess_000015,churned,2024-05-22 21:01:09,desktop,organic,2024-04,returning,churn,3.0,50
116,user_0002,sess_000018,churned,2024-03-24 12:05:48,desktop,paid_search,2024-03,new,churn,3.0,12
152,user_0003,sess_000021,churned,2024-03-23 21:34:30,desktop,paid_search,2024-02,returning,churn,3.0,25

### add_segment — CASE-WHEN rules

Docs: [Add Segment](https://retentioneering.com/docs/data-processors/add-segment).

A *segment column* names a segmentation; each value is one segment (static or dynamic — see [Key concepts](https://retentioneering.com/docs/eventstream#key-concepts)). `rules` is a list of `[column, op, value, label]` conditions plus a final `[else_label]` entry.

In [40]:
res = stream.add_segment(
    "channel_type",
    rules=[
        ["acquisition_channel", "in", "('paid_search', 'social', 'email')", "paid"],
        ["organic_or_direct"],
    ],
)
peek(res)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index,channel_type
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1,paid
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2,paid
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3,paid
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4,paid
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5,paid
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6,paid
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7,paid
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8,paid
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9,paid
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10,paid

### add_segment — Python function

`func` gets the raw DataFrame and returns one label per row. Because labels are assigned per **row**, segments can be *dynamic* — here the value changes along the path depending on the event's weekday.

In [41]:
res = stream.add_segment(
    "day_type",
    func=lambda d: (d["timestamp"].dt.dayofweek >= 5).map(
        {True: "weekend", False: "weekday"}
    ),
)
peek(res)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index,day_type
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1,weekday
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2,weekday
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3,weekday
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4,weekday
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5,weekday
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6,weekday
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7,weekday
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8,weekday
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9,weekday
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10,weekday

### add_segment — SQL

The query (alias `eventstream`) must return exactly one column with one label per row, in the original row order. Window functions are supported.

In [42]:
res = stream.add_segment(
    "session_size",
    sql="""
        SELECT CASE WHEN COUNT(*) OVER (PARTITION BY session_id) >= 10
                    THEN 'long_session' ELSE 'short_session' END
        FROM eventstream
    """,
)
peek(res)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index,session_size
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1,long_session
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2,long_session
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3,long_session
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4,long_session
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5,long_session
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6,long_session
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7,long_session
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8,long_session
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9,long_session
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10,long_session

### add_segment — funnel stage

`funnel_events` assigns each path the name of the **last funnel step reached in sequence** (or `out_of_funnel`). Handy for drop-off analysis: diff the paths that stopped at step N against those that reached N+1.

In [43]:
res = stream.add_segment(
    "funnel_stage", funnel_events=["add_to_cart", "payment_details", "purchase"]
)
print(res.to_dataframe().groupby("funnel_stage", observed=True)["user_id"].nunique())
peek(res)

funnel_stage
add_to_cart        132
out_of_funnel       78
payment_details     62
purchase           328
Name: user_id, dtype: int64

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index,funnel_stage
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1,purchase
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2,purchase
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3,purchase
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4,purchase
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5,purchase
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6,purchase
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7,purchase
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8,purchase
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9,purchase
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10,purchase

### add_clusters — ML segment from behavioral features

Docs: [Add Clusters](https://retentioneering.com/docs/data-processors/add-clusters).

Computes per-path metrics (`features`), scales them (`minmax` / `standard` / `None`), clusters (`method_args` carries the chosen `method`'s own parameters: `n_clusters` for `kmeans`, `min_cluster_size` / `cluster_selection_epsilon` for `hdbscan`), and broadcasts the label to every row of the path. `nmf_components` optionally reduces features with NMF first. For interactive exploration use the [Cluster Analysis widget](https://retentioneering.com/docs/widgets/cluster-analysis) instead.

In [44]:
clustered = stream.add_clusters(
    name="behavior_cluster",
    features=[
        {"metric": "length"},
        {
            "metric": "event_count_bulk",
            "metric_args": {"events": ["purchase", "add_to_cart", "search"]},
        },
    ],
    method="kmeans",
    method_args={"n_clusters": 4},
    scaler="minmax",
)
print(
    clustered.to_dataframe()
    .groupby("behavior_cluster", observed=True)["user_id"]
    .nunique()
)
peek(clustered)

behavior_cluster
cluster_0    159
cluster_1     85
cluster_2    152
cluster_3    204
Name: user_id, dtype: int64

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index,behavior_cluster
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1,cluster_1
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2,cluster_1
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3,cluster_1
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4,cluster_1
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5,cluster_1
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6,cluster_1
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7,cluster_1
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8,cluster_1
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9,cluster_1
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10,cluster_1

### drop_segment

Removes a segment column added earlier (or declared in the schema).

In [45]:
res = clustered.drop_segment("behavior_cluster")
print("segments:", res.schema.segment_cols)
peek(res)

segments: ['platform', 'acquisition_channel', 'user_cohort', 'user_lifecycle']

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10

### collapse_events — self-loops

Docs: [Collapse Events](https://retentioneering.com/docs/data-processors/collapse-events).

Two independent decisions. **Which rows belong together** is one mutually exclusive mode: `loops` / `group_col` group adjacent rows sharing a value, `event_groups` / `bounds` cut the path into windows, `bounds` spelled as in `split_sessions`. **What the merged event is called** is `name`, orthogonal to all of them.

`loops=True` merges each self-loop — a run of the same event repeating, the `A → A` of a transition graph (`product_view -> product_view -> product_view` becomes one row); pass a list of event names to collapse only those.

In [46]:
res = stream.collapse_events(loops=True)
print(f"rows: {len(stream.to_dataframe()):,} -> {len(res.to_dataframe()):,}")
peek(res, user=USER)

rows: 31,106 -> 27,937

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,index,subindex
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,1,2.0
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2,2.0
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,3,2.0
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,4,2.0
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,5,2.0
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,collapsed,6,2.0
6,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,10,2.0
7,user_0000,sess_000001,catalog,2024-03-13 10:35:48,desktop,email,2024-01,returning,raw,11,2.0
8,user_0000,sess_000002,product_view,2024-03-23 09:44:28,desktop,email,2024-01,returning,raw,12,2.0
9,user_0000,sess_000002,add_to_cart,2024-03-23 09:46:40,desktop,email,2024-01,returning,raw,13,2.0

### collapse_events — a group of related events

`event_groups` names the events that belong to one group: any run drawn from that set merges into a single event, taking the group's first timestamp. Unlike `loops`, the run may mix them — `["a", "b"]` turns `a, a, b, b` into one event where `loops` would give two. `name` labels the result.

In [47]:
res = stream.collapse_events(
    event_groups=["payment_details", "shipping_details", "review_page"],
    name="checkout",
)
peek(res, user=USER)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,index,subindex
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,1,2.0
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2,2.0
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,3,2.0
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,4,2.0
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,5,2.0
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,6,2.0
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,7,2.0
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,8,2.0
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,9,2.0
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,10,2.0

### collapse_events — runs of a column value

`group_col` collapses each run of adjacent rows sharing the same column value into one event, **named after that value** by default. Here we first label rows as `browse`/`action` and then collapse the path into alternating stages.

In [48]:
staged = stream.add_segment(
    "screen_type",
    rules=[
        [
            "event",
            "in",
            "('home', 'catalog', 'search', 'filter_results', 'product_view', 'compare', 'promo_page')",
            "browse",
        ],
        ["action"],
    ],
)
res = staged.collapse_events(group_col="screen_type")
peek(res, user=USER)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,screen_type,event_type,index,subindex
0,user_0000,sess_000001,browse,2024-03-13 10:21:14,desktop,email,2024-01,returning,browse,collapsed,1,2.0
1,user_0000,sess_000001,action,2024-03-13 10:23:35,desktop,email,2024-01,returning,action,collapsed,4,2.0
2,user_0000,sess_000001,browse,2024-03-13 10:25:07,desktop,email,2024-01,returning,browse,collapsed,5,2.0
3,user_0000,sess_000002,action,2024-03-23 09:46:40,desktop,email,2024-01,returning,action,collapsed,13,2.0
4,user_0000,sess_000003,browse,2024-04-21 17:51:34,desktop,email,2024-01,loyal,browse,collapsed,18,2.0
5,user_0000,sess_000004,action,2024-04-27 16:46:45,desktop,email,2024-01,loyal,action,collapsed,21,2.0
6,user_0000,sess_000005,browse,2024-04-30 19:33:58,desktop,email,2024-01,loyal,browse,collapsed,23,2.0
7,user_0000,sess_000005,action,2024-04-30 19:34:13,desktop,email,2024-01,loyal,action,collapsed,24,2.0
8,user_0000,sess_000006,browse,2024-05-07 13:10:22,desktop,email,2024-01,loyal,browse,collapsed,26,2.0
9,user_0000,sess_000006,action,2024-05-07 13:13:45,desktop,email,2024-01,loyal,action,collapsed,28,2.0

### collapse_events — one event per session, named by what it did

`group_col="session_id"` gives one event per session; `name` says what to call it. As a list of cases it is evaluated against each session's own events, so the label comes from what happened inside — no precomputed session-type column needed.

In [49]:
res = stream.collapse_events(
    group_col="session_id",
    name=[
        {
            "condition": {
                "op": "=",
                "metric": "has_event",
                "value": True,
                "metric_args": {"event": "purchase"},
            },
            "name": "buying_session",
        },
        "browsing_session",
    ],
)
peek(res, user=USER)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,index,subindex
0,user_0000,sess_000001,browsing_session,2024-03-13 10:21:14,desktop,email,2024-01,returning,collapsed,1,2.0
1,user_0000,sess_000002,buying_session,2024-03-23 09:44:28,desktop,email,2024-01,returning,collapsed,12,2.0
2,user_0000,sess_000003,browsing_session,2024-04-21 17:51:34,desktop,email,2024-01,loyal,collapsed,18,2.0
3,user_0000,sess_000004,browsing_session,2024-04-27 16:46:21,desktop,email,2024-01,loyal,collapsed,20,2.0
4,user_0000,sess_000005,browsing_session,2024-04-30 19:33:58,desktop,email,2024-01,loyal,collapsed,23,2.0
5,user_0000,sess_000006,browsing_session,2024-05-07 13:10:22,desktop,email,2024-01,loyal,collapsed,26,2.0
6,user_0000,sess_000007,buying_session,2024-06-12 16:23:57,desktop,email,2024-01,loyal,collapsed,34,2.0
7,user_0000,sess_000008,buying_session,2024-06-18 19:12:42,desktop,email,2024-01,loyal,collapsed,40,2.0

### rename_events / drop_events / edit_events

Docs: [Rename Events](https://retentioneering.com/docs/data-processors/rename-events), [Drop Events](https://retentioneering.com/docs/data-processors/drop-events), [Edit Events](https://retentioneering.com/docs/data-processors/edit-events).

`rename_events` maps old names to new ones; `drop_events` removes events by name (unknown names raise); `edit_events` does both in one pass.

In [50]:
res = stream.rename_events({"wishlist_add": "add_to_wishlist", "cart": "cart_view"})
peek(res)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10

In [51]:
res = stream.drop_events(["support_chat", "error_page"])
print("events left:", res.to_dataframe()["event"].astype(str).nunique())
peek(res)

events left: 17

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10

In [52]:
res = stream.edit_events(rename={"promo_page": "promo"}, delete=["account_page"])
peek(res)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
1,user_0000,sess_000001,promo,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
4,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5
5,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6
6,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7
7,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8
8,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9
9,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10

### sample_paths — by count

Docs: [Sample Paths](https://retentioneering.com/docs/data-processors/sample-paths).

Randomly samples whole paths (all their events survive). Mirrors `pandas.DataFrame.sample`: `n` for a count, `frac` for a share, and `random_state` for reproducibility.

In [53]:
res = stream.sample_paths(n=100, random_state=42)
print("users:", res.to_dataframe()["user_id"].nunique())
peek(res)

users: 100

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0005,sess_000031,catalog,2024-05-19 12:33:07,mobile,paid_search,2024-04,returning,raw,2.0,1
1,user_0005,sess_000032,home,2024-06-04 15:13:52,mobile,paid_search,2024-04,returning,raw,2.0,2
2,user_0005,sess_000032,catalog,2024-06-04 15:14:16,mobile,paid_search,2024-04,returning,raw,2.0,3
3,user_0005,sess_000032,product_view,2024-06-04 15:16:07,mobile,paid_search,2024-04,returning,raw,2.0,4
4,user_0005,sess_000032,add_to_cart,2024-06-04 15:16:53,mobile,paid_search,2024-04,returning,raw,2.0,5
5,user_0005,sess_000032,catalog,2024-06-04 15:18:57,mobile,paid_search,2024-04,returning,raw,2.0,6
6,user_0005,sess_000032,filter_results,2024-06-04 15:20:20,mobile,paid_search,2024-04,returning,raw,2.0,7
7,user_0005,sess_000032,catalog,2024-06-04 15:21:47,mobile,paid_search,2024-04,returning,raw,2.0,8
8,user_0005,sess_000032,product_view,2024-06-04 15:23:52,mobile,paid_search,2024-04,returning,raw,2.0,9
9,user_0005,sess_000033,home,2024-06-09 13:31:57,mobile,paid_search,2024-04,returning,raw,2.0,10

### sample_paths — by fraction

In [54]:
res = stream.sample_paths(frac=0.2, random_state=42)
print("users:", res.to_dataframe()["user_id"].nunique())
peek(res)

users: 120

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0002,sess_000017,home,2024-03-20 19:38:38,desktop,paid_search,2024-03,new,raw,2.0,1
1,user_0002,sess_000017,search,2024-03-20 19:40:52,desktop,paid_search,2024-03,new,raw,2.0,2
2,user_0002,sess_000017,catalog,2024-03-20 19:41:39,desktop,paid_search,2024-03,new,raw,2.0,3
3,user_0002,sess_000017,product_view,2024-03-20 19:43:32,desktop,paid_search,2024-03,new,raw,2.0,4
4,user_0002,sess_000017,add_to_cart,2024-03-20 19:46:25,desktop,paid_search,2024-03,new,raw,2.0,5
5,user_0002,sess_000018,home,2024-03-24 11:57:46,desktop,paid_search,2024-03,new,raw,2.0,6
6,user_0002,sess_000018,catalog,2024-03-24 11:59:31,desktop,paid_search,2024-03,new,raw,2.0,7
7,user_0002,sess_000018,product_view,2024-03-24 12:01:56,desktop,paid_search,2024-03,new,raw,2.0,8
8,user_0002,sess_000018,catalog,2024-03-24 12:02:23,desktop,paid_search,2024-03,new,raw,2.0,9
9,user_0002,sess_000018,catalog,2024-03-24 12:02:49,desktop,paid_search,2024-03,new,raw,2.0,10

### split_sessions — inactivity timeout

Docs: [Split Sessions](https://retentioneering.com/docs/data-processors/split-sessions).

Adds `session_id` / `session_index` columns (names configurable via `session_col` / `session_index_col`). Three boundary modes: `timeout`, `separator`, and `bounds` (`{"start_event": ..., "end_event": ...}`); `timeout` can be combined with either of the other two. `timeout` takes a duration **string with an explicit unit** (`"30m"`, `"1h"`, `"1800s"`) or a `pandas.Timedelta` — bare numbers are rejected to avoid unit ambiguity. The ecom dataset already carries sessions, so these cells work on a flattened copy without them.

In [55]:
flat = rete.Eventstream(df[["user_id", "event", "timestamp"]].copy())

res = flat.split_sessions(timeout="30m")
peek(res, user=USER, n=12)

,user_id,event,timestamp,event_type,index,subindex,session_index,session_id
0,user_0000,home,2024-03-13 10:21:14,raw,1,2.0,1,user_0000_1
1,user_0000,promo_page,2024-03-13 10:21:58,raw,2,2.0,1,user_0000_1
2,user_0000,product_view,2024-03-13 10:22:42,raw,3,2.0,1,user_0000_1
3,user_0000,add_to_cart,2024-03-13 10:23:35,raw,4,2.0,1,user_0000_1
4,user_0000,catalog,2024-03-13 10:25:07,raw,5,2.0,1,user_0000_1
5,user_0000,product_view,2024-03-13 10:26:18,raw,6,2.0,1,user_0000_1
6,user_0000,product_view,2024-03-13 10:27:37,raw,7,2.0,1,user_0000_1
7,user_0000,product_view,2024-03-13 10:29:50,raw,8,2.0,1,user_0000_1
8,user_0000,product_view,2024-03-13 10:30:44,raw,9,2.0,1,user_0000_1
9,user_0000,search,2024-03-13 10:33:29,raw,10,2.0,1,user_0000_1
10,user_0000,catalog,2024-03-13 10:35:48,raw,11,2.0,1,user_0000_1
11,user_0000,product_view,2024-03-23 09:44:28,raw,12,2.0,2,user_0000_2

### split_sessions — separator event

The separator event starts a new session and is dropped from the output — natural when the log has an explicit "app opened / landing" event; here `home` plays that role.

In [56]:
res = flat.split_sessions(separator="home")
peek(res, user=USER, n=12)

,user_id,event,timestamp,event_type,index,subindex,session_index,session_id
0,user_0000,promo_page,2024-03-13 10:21:58,raw,2,2.0,1,user_0000_1
1,user_0000,product_view,2024-03-13 10:22:42,raw,3,2.0,1,user_0000_1
2,user_0000,add_to_cart,2024-03-13 10:23:35,raw,4,2.0,1,user_0000_1
3,user_0000,catalog,2024-03-13 10:25:07,raw,5,2.0,1,user_0000_1
4,user_0000,product_view,2024-03-13 10:26:18,raw,6,2.0,1,user_0000_1
5,user_0000,product_view,2024-03-13 10:27:37,raw,7,2.0,1,user_0000_1
6,user_0000,product_view,2024-03-13 10:29:50,raw,8,2.0,1,user_0000_1
7,user_0000,product_view,2024-03-13 10:30:44,raw,9,2.0,1,user_0000_1
8,user_0000,search,2024-03-13 10:33:29,raw,10,2.0,1,user_0000_1
9,user_0000,catalog,2024-03-13 10:35:48,raw,11,2.0,1,user_0000_1
10,user_0000,product_view,2024-03-23 09:44:28,raw,12,2.0,1,user_0000_1
11,user_0000,add_to_cart,2024-03-23 09:46:40,raw,13,2.0,1,user_0000_1

### split_sessions — bounds

Sessions span from a `start_event` to an `end_event`, passed together as `bounds`; rows outside any such span get an empty session. Best when the log has explicit markers — here we use `home -> purchase` spans purely to show the mechanics.

In [57]:
res = flat.split_sessions(bounds={"start_event": "home", "end_event": "purchase"})
peek(res, user=USER, n=12)

,user_id,event,timestamp,event_type,index,subindex,session_index,session_id
0,user_0000,promo_page,2024-03-13 10:21:58,raw,2,2.0,1,user_0000_1
1,user_0000,product_view,2024-03-13 10:22:42,raw,3,2.0,1,user_0000_1
2,user_0000,add_to_cart,2024-03-13 10:23:35,raw,4,2.0,1,user_0000_1
3,user_0000,catalog,2024-03-13 10:25:07,raw,5,2.0,1,user_0000_1
4,user_0000,product_view,2024-03-13 10:26:18,raw,6,2.0,1,user_0000_1
5,user_0000,product_view,2024-03-13 10:27:37,raw,7,2.0,1,user_0000_1
6,user_0000,product_view,2024-03-13 10:29:50,raw,8,2.0,1,user_0000_1
7,user_0000,product_view,2024-03-13 10:30:44,raw,9,2.0,1,user_0000_1
8,user_0000,search,2024-03-13 10:33:29,raw,10,2.0,1,user_0000_1
9,user_0000,catalog,2024-03-13 10:35:48,raw,11,2.0,1,user_0000_1
10,user_0000,product_view,2024-03-23 09:44:28,raw,12,2.0,1,user_0000_1
11,user_0000,add_to_cart,2024-03-23 09:46:40,raw,13,2.0,1,user_0000_1

### truncate_paths — window between two anchor events

Docs: [Truncate Paths](https://retentioneering.com/docs/data-processors/truncate-paths).

Keeps, per path, the window from the first `start_anchor` to the first `end_anchor` after it (inclusive); paths without both anchors in order are removed. The reserved names `path_start` / `path_end` work as anchors too.

In [58]:
res = stream.truncate_paths(start_anchor="add_to_cart", end_anchor="purchase")
print("users kept:", res.to_dataframe()["user_id"].nunique())
peek(res, user=USER)

users kept: 328

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
1,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5
2,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6
3,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7
4,user_0000,sess_000001,product_view,2024-03-13 10:29:50,desktop,email,2024-01,returning,raw,2.0,8
5,user_0000,sess_000001,product_view,2024-03-13 10:30:44,desktop,email,2024-01,returning,raw,2.0,9
6,user_0000,sess_000001,search,2024-03-13 10:33:29,desktop,email,2024-01,returning,raw,2.0,10
7,user_0000,sess_000001,catalog,2024-03-13 10:35:48,desktop,email,2024-01,returning,raw,2.0,11
8,user_0000,sess_000002,product_view,2024-03-23 09:44:28,desktop,email,2024-01,returning,raw,2.0,12
9,user_0000,sess_000002,add_to_cart,2024-03-23 09:46:40,desktop,email,2024-01,returning,raw,2.0,13

In [59]:
# path_start / path_end sentinels work as anchors too
res = stream.truncate_paths(start_anchor="path_start", end_anchor="add_to_cart")
print("users kept:", res.to_dataframe()["user_id"].nunique())
peek(res, user=USER)

users kept: 522

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
1,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
2,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
3,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4

### to_daily_states — lifecycle resampling

Docs: [To Daily States](https://retentioneering.com/docs/data-processors/to-daily-states).

Converts the stream into one row per path per calendar day, labelled with an engagement state: active days are `new` / `current` / `reactivated` / `resurrected`, inactive days are `at_risk_wau` / `at_risk_mau` / `dormant`. `active_events` restricts what counts as activity; `max_dormant_days` caps how long rows are generated after the last event.

In [60]:
daily = stream.to_daily_states(
    active_events=["catalog", "add_to_cart", "purchase"], max_dormant_days=14
)
print(daily.to_dataframe()["event"].value_counts())
peek(daily, user=USER, n=12)

event
at_risk_mau    24494
at_risk_wau    17523
dormant        11341
reactivated     1239
current          792
new              600
resurrected      461
Name: count, dtype: int64

,user_id,timestamp,session_id,event,event_type,subindex,index,platform,acquisition_channel,user_cohort,user_lifecycle
0,user_0000,2024-03-13,<NA>,new,collapsed,1.0,1,desktop,email,2024-01,returning
1,user_0000,2024-03-14,<NA>,at_risk_wau,collapsed,1.0,2,desktop,email,2024-01,returning
2,user_0000,2024-03-15,<NA>,at_risk_wau,collapsed,1.0,3,desktop,email,2024-01,returning
3,user_0000,2024-03-16,<NA>,at_risk_wau,collapsed,1.0,4,desktop,email,2024-01,returning
4,user_0000,2024-03-17,<NA>,at_risk_wau,collapsed,1.0,5,desktop,email,2024-01,returning
5,user_0000,2024-03-18,<NA>,at_risk_wau,collapsed,1.0,6,desktop,email,2024-01,returning
6,user_0000,2024-03-19,<NA>,at_risk_wau,collapsed,1.0,7,desktop,email,2024-01,returning
7,user_0000,2024-03-20,<NA>,at_risk_wau,collapsed,1.0,8,desktop,email,2024-01,returning
8,user_0000,2024-03-21,<NA>,at_risk_mau,collapsed,1.0,9,desktop,email,2024-01,returning
9,user_0000,2024-03-22,<NA>,at_risk_mau,collapsed,1.0,10,desktop,email,2024-01,returning
10,user_0000,2024-03-23,<NA>,reactivated,collapsed,1.0,11,desktop,email,2024-01,returning
11,user_0000,2024-03-24,<NA>,at_risk_wau,collapsed,1.0,12,desktop,email,2024-01,returning

### add_start_end_events

Docs: [Add Start End Events](https://retentioneering.com/docs/data-processors/add-start-end-events).

Prepends `path_start` and appends `path_end` to each path (idempotent). You rarely call it yourself — the widgets insert these markers on the fly, each respecting its own `path_col`.

In [61]:
res = stream.add_start_end_events()
out = res.to_dataframe(exclude_start_end=False)  # keep the markers visible
out[out["user_id"] == USER].head(8)

,user_id,session_id,event,timestamp,platform,acquisition_channel,user_cohort,user_lifecycle,event_type,subindex,index
0,user_0000,sess_000001,path_start,2024-03-13 10:21:14,desktop,email,2024-01,returning,path_start,0.0,1
1,user_0000,sess_000001,home,2024-03-13 10:21:14,desktop,email,2024-01,returning,raw,2.0,1
2,user_0000,sess_000001,promo_page,2024-03-13 10:21:58,desktop,email,2024-01,returning,raw,2.0,2
3,user_0000,sess_000001,product_view,2024-03-13 10:22:42,desktop,email,2024-01,returning,raw,2.0,3
4,user_0000,sess_000001,add_to_cart,2024-03-13 10:23:35,desktop,email,2024-01,returning,raw,2.0,4
5,user_0000,sess_000001,catalog,2024-03-13 10:25:07,desktop,email,2024-01,returning,raw,2.0,5
6,user_0000,sess_000001,product_view,2024-03-13 10:26:18,desktop,email,2024-01,returning,raw,2.0,6
7,user_0000,sess_000001,product_view,2024-03-13 10:27:37,desktop,email,2024-01,returning,raw,2.0,7

### urls_to_events — structured events from raw URLs

Docs: [URLs to Events](https://retentioneering.com/docs/data-processors/urls-to-events).

Turns a URL column into event names using a path tree. Node keys: `aggregate_children` collapses deeper pages into `<path>/<slug>`; `exclude` drops the subtree; `name` sets a custom label/slug. `strip_host` / `strip_query` / `strip_locale` (all default `True`) normalize the URL first. The ecom dataset has no URLs, so this cell uses a tiny synthetic log.

In [62]:
url_df = pd.DataFrame(
    {
        "user_id": ["u1"] * 6,
        "event": ["page_view"] * 6,
        "timestamp": pd.date_range("2024-01-01 10:00", periods=6, freq="1min"),
        "url": [
            "https://shop.example.com/en/catalog/phones/iphone-15",
            "https://shop.example.com/en/catalog/laptops",
            "https://shop.example.com/en/cart",
            "https://shop.example.com/en/checkout/payment?step=2",
            "https://shop.example.com/en/admin/debug",
            "https://shop.example.com/en/checkout/confirm",
        ],
    }
)
url_stream = rete.Eventstream(url_df, schema={"custom_cols": ["url"]})

res = url_stream.urls_to_events(
    column="url",
    nodes=[
        {"path": "/catalog", "aggregate_children": True},
        {"path": "/catalog/phones", "name": "phones"},
        {"path": "/checkout", "aggregate_children": True},
        {"path": "/admin", "exclude": True},
    ],
)
res.to_dataframe()

,user_id,event,timestamp,url,event_type,subindex,index
0,u1,page_view:/catalog/phones,2024-01-01 10:00:00,https://shop.example.com/en/catalog/phones/iph...,raw,2.0,1
1,u1,page_view:/catalog/sub-page,2024-01-01 10:01:00,https://shop.example.com/en/catalog/laptops,raw,2.0,2
2,u1,page_view:/cart,2024-01-01 10:02:00,https://shop.example.com/en/cart,raw,2.0,3
3,u1,page_view:/checkout/sub-page,2024-01-01 10:03:00,https://shop.example.com/en/checkout/payment?s...,raw,2.0,4
5,u1,page_view:/checkout/sub-page,2024-01-01 10:05:00,https://shop.example.com/en/checkout/confirm,raw,2.0,6

## 4. Path metrics

Docs: [Path Metrics](https://retentioneering.com/docs/path-metrics).

One registry of per-path scalar metrics powers `filter_paths`, `add_clusters`, Segment Overview, and Cluster Analysis — and is available raw via `get_metrics()` (e.g. as ML features). The cell below reuses `FULL_METRICS`, defined earlier — every metric in the registry once.

In [63]:
metrics = stream.get_metrics(FULL_METRICS)
metrics.head(8)

,length,duration,event_count_purchase,has_event_purchase,event_count_bulk_purchase,event_count_bulk_add_to_cart,event_count_bulk_search,has_event_bulk_purchase,has_event_bulk_add_to_cart,has_event_bulk_search,has_all_events_add_to_cart_and_purchase,has_any_event_promo_page_or_wishlist_add,time_from_path_start_to_purchase,first_event_time,active_days,matches_pattern_search->.*->purchase,in_segment_user_lifecycle_loyal_any
user_id,,,,,,,,,,,,,,,,,
user_0000,45,8413215.0,3,1,3,6,2,1,1,1,1,1,862238.0,1.710325e+09,8,True,1
user_0001,56,6394871.0,0,0,0,4,9,0,1,1,0,1,NaN,1.712934e+09,8,False,0
user_0002,22,8085626.0,1,1,1,3,1,1,1,1,1,0,8085626.0,1.710964e+09,3,True,1
user_0003,75,7106017.0,2,1,2,3,8,1,1,1,1,1,560628.0,1.710669e+09,7,True,1
user_0004,40,9208561.0,1,1,1,3,6,1,1,1,1,1,851.0,1.709846e+09,4,False,1
user_0005,44,1995074.0,0,0,0,2,9,0,1,1,0,0,NaN,1.716122e+09,4,False,0
user_0006,96,11076024.0,0,0,0,3,13,0,1,1,0,1,NaN,1.705395e+09,9,False,1
user_0007,17,4419590.0,0,0,0,0,2,0,0,1,0,1,NaN,1.714586e+09,3,False,0

### get_metric_distribution

Distribution of one metric for one segment level vs. its complement (`segment_level=`) or for two levels vs. each other (`segment_levels=[a, b]`) — the same computation behind Segment Overview's clickable cells. Returns histogram bins/counts, KDE, and the Wasserstein distance.

In [64]:
dist = stream.get_metric_distribution(
    segment_col="platform",
    metric={"metric": "length"},
    segment_level="mobile",  # mobile vs. everyone else
)
print("keys:", list(dist.keys()))
print("distance (mobile vs rest):", round(dist["distance"], 3))

keys: ['distribution_1', 'distribution_2', 'distance', 'log_scale']
distance (mobile vs rest): 2.223

## Where to go next

- [Documentation](https://retentioneering.com/docs/) — guides and the full API reference.
- `ecom_demo.ipynb` — a narrative walkthrough of the same dataset: stories,
  anomalies, and how to investigate them with these tools.
- [MCP server](https://retentioneering.com/docs/mcp-server) — `retentioneering.mcp.serve(stream)` exposes the
  eventstream to Claude or any MCP client for agent-driven analysis.